### PR TITLE
Move data to companies directory

### PR DESCRIPTION
**Pull request by AmirHosseinKarimi**
Prevent long list of directories in default page of repository.

### CODE REVIEW

**Comment by AmirHosseinKarimi** [comment]
Some directories & files contain invalid encoding characters which this PR will fix them.
Company details file which previously named as company, now renamed to **info**.
All files content reformatted.
Add files extension (.json) to readable by Windows users easily.

**Comment by AmirHosseinKarimi** [comment]
Add reviews with full details, reviews in company directory was truncated and does not contain some properties like pros & cons.

**Comment by masoud-msk** [comment]
@AmirHosseinKarimi Will you also add full interviews?

**Comment by AmirHosseinKarimi** [comment]
@masoud-msk Of course. Also interviews comments.
Any other data we can scrap and store.

Update: they was added. #3

**Pull request merged**
